version: '3'

services:

  hosoy-metasql:
    image: mysql:8.0
    container_name: hosoy-metasql
    hostname: hosoy-metasql
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 64M
    environment:
      MYSQL_ROOT_PASSWORD: hivemeta
      MYSQL_DATABASE: metastore_db
    ports:
      - "6612:3306"
    networks:
      hosoy-network:
        ipv4_address: 172.18.0.21

  hosoy-master:
    image: hosoy:0.0.2
    hostname: hosoy-master
    container_name: hosoy-master
    depends_on:
      - hosoy-metasql
    environment:
      - MODE=master
      - SPARK_MASTER_HOST=hosoy-master
      - SPARK_MASTER_PORT=7077
    ports:
      - "2022:22"
      - "7077:7077"
      - "8088:8088"
      - "4040:4040"
      - "28080:8080"
      - "8042:8042"
      - "18080:18080"
      - "9870:9870"
    networks:
      hosoy-network:
        ipv4_address: 172.18.0.20
    extra_hosts:
      - "hosoy-master:172.18.0.20"
      - "hosoy-metasql:172.18.0.21"

  hosoy-metastore:
    image: hosoy:0.0.2
    container_name: hosoy-metastore
    hostname: hosoy-metastore
    depends_on:
      - hosoy-metasql
      - hosoy-master
    environment:
      - MODE=metastore
    networks:
      hosoy-network:
        ipv4_address: 172.18.0.22
    ports:
      - "9083:9083"
    extra_hosts:
      - "hosoy-master:172.18.0.20"
      - "hosoy-metasql:172.18.0.21"
      - "hosoy-metastore:172.18.0.22"

  slave:
    image: hosoy:0.0.2
    depends_on:
      - hosoy-metasql
      - hosoy-master
      - hosoy-metastore
    environment:
      - MODE=slave
    ports:
      - "22"
      - "7177"
      - "7077"
      - "8042"
    networks:
      - hosoy-network
    extra_hosts:
      - "hosoy-master:172.18.0.20"
      - "hosoy-metasql:172.18.0.21"
      - "hosoy-metastore:172.18.0.22"

  sparksql:
    image: hosoy:0.0.2
    depends_on:
      - hosoy-metasql
      - hosoy-master
      - hosoy-metastore
      - slave
    environment:
      - MODE=sparksql
      - HOLDING_TIME=120
    ports:
      - "10016:10000"
    networks:
      - hosoy-network
    extra_hosts:
      - "hosoy-master:172.18.0.20"
      - "hosoy-metasql:172.18.0.21"
      - "hosoy-metastore:172.18.0.22"

networks:
  hosoy-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
